### ISSUE TITLE
Bullet point không hiển thị khi publish bài post

### ISSUE THREAD

**Issue by sylarbui** [OCPVietnam/main-bug#11]
## Issue summary
Trong phần editor, khi dùng bullet point, thì nó sẽ không show khi bài post/page được publish. Nhưng trong phần editor vẫn có.

## Screenshot (recommended)
Ví dụ: Trong bài này, anh đang dùng bullet point nhưng phải đáng thêm số để khi publish thì số sẽ hiện do bullet point không hiển thị.

<img width="1440" alt="Screen Shot 2019-05-17 at 15 57 34" src="https://user-images.githubusercontent.com/40219472/57916278-b5c0b180-78bc-11e9-8b0f-51ed70b48080.png">
<img width="1440" alt="Screen Shot 2019-05-17 at 15 57 13" src="https://user-images.githubusercontent.com/40219472/57916281-b6f1de80-78bc-11e9-9a2f-ee57649425b2.png">

## Additional information
https://ocpvn.org/thong-tin-co-ban-ve-ban-quyen-va-imprimatur/

**Comment by vyvy0812** [comment]
http://prntscr.com/nqwvgb đã hiện Bullet point

**Comment by sylarbui** [comment]
Thanks em~
