### ISSUE TITLE
Sai PDF của bài hát khi nhấn download

### ISSUE THREAD

**Issue by sylarbui** [OCPVietnam/main-bug#2]
## Issue summary
- Khi nhấn download PDF trong trang bài hát thì hiện sai file PDF. 
- Đã check URL trong admin page: đúng link PDF.
- Khi back & nhấn download lại thì ra đúng file PDF.

## Screencast (recommended)
http://recordit.co/OdzwSyUYio

Admin Page:
<img width="1440" alt="screen shot 2019-01-06 at 08 50 29" src="https://user-images.githubusercontent.com/40219472/50731148-2679f380-1190-11e9-9ad7-3b5181332bcd.png">

## Additional information
Link: https://ocpvn.org/bai-hat/this-holy-light/

**Comment by vyvy0812** [comment]
Done https://youtu.be/O43ZgDOHZI0
