### ISSUE TITLE
Lỗi hiển thị khi tạo trang mới

### ISSUE THREAD

**Issue by sylarbui** [OCPVietnam/main-bug#5]
## Issue summary
**1. Khoảng cách giữa tiêu đề và page banner bị lỗi dính vào nhau khi đăng lên.** 

Admin page: 
<img width="1440" alt="screen shot 2019-01-21 at 15 53 42" src="https://user-images.githubusercontent.com/40219472/51464006-36e8bb80-1d97-11e9-83f7-817d9795fe62.png">

Page đã đăng:
<img width="1440" alt="screen shot 2019-01-21 at 15 54 01" src="https://user-images.githubusercontent.com/40219472/51464138-7adbc080-1d97-11e9-907e-ac7f0cfb2057.png">

**2. Dấu chấm đầu câu không hiển thị khi đăng bài.**
Admin page: 
<img width="1080" alt="screen shot 2019-01-21 at 15 57 29" src="https://user-images.githubusercontent.com/40219472/51464188-92b34480-1d97-11e9-9ce4-36d70342918c.png">

Bài đã đăng:
<img width="1335" alt="screen shot 2019-01-21 at 16 14 41" src="https://user-images.githubusercontent.com/40219472/51464268-bbd3d500-1d97-11e9-8aed-791d66708207.png">

## Additional information
Link: https://ocpvn.org/hoc-thuat/thinh-lang-trong-cu-hanh-phung-vu/

**Comment by vyvy0812** [comment]
Các phần fix  xong: 
1. Khoảng cách giữa tiêu đề và page banner bị lỗi dính vào nhau khi đăng lên --> http://prntscr.com/m9z2oa 
2. Dấu chấm đầu câu không hiển thị khi đăng bài--> http://prntscr.com/m9z3in

**Comment by sylarbui** [comment]
Thanks e @vyvy0812
