### ISSUE TITLE
Page banner đang bị mặc định của "Song Ngữ/Đa Văn Hóa"

### ISSUE THREAD

**Issue by sylarbui** [OCPVietnam/main-bug#6]
## Issue summary
Khi tạo post mới thì page banner luôn bị mặc định là của "Song Ngữ/Đa Văn Hóa"

## Screencast (recommended)
http://recordit.co/pLNdhQNTEW

**Comment by vyvy0812** [comment]
Done. http://prntscr.com/m9z6ic

**Comment by sylarbui** [comment]
@vyvy0812 ý anh là khi tạo bất kì bài post nào, thì page banner vẫn luôn là "Song Ngữ/Đa Văn Hóa", anh ko đổi tên được.

VD: đây là bài post anh mới tạo trong Học Thuật:
<img width="1438" alt="screen shot 2019-01-22 at 00 36 31" src="https://user-images.githubusercontent.com/40219472/51490557-3aebfc00-1dde-11e9-9593-67973abef6cb.png">


Link: https://ocpvn.org/vietnamese-catholicism-english-article/

**Comment by vyvy0812** [comment]
http://prntscr.com/mjdpcx done, nếu chọn đồng thời 2 danh mục cha con thì sẽ tên banner sẽ là tên của danh mục cha

**Comment by sylarbui** [comment]
@vyvy0812 hình như vẫn chưa được nha em, em check lại giúp anh hen. Anh mới thấy thêm issue là page đã chọn danh mục rồi mà banner không xuất hiện

https://ocpvn.org/gio-thanh-le-tieng-anh-tai-viet-nam/

**Comment by vyvy0812** [comment]
Đã hiện page banner http://prntscr.com/nqwtbz

**Comment by sylarbui** [comment]
Thanks la~ Đã fixed nha.
