### ISSUE TITLE
Google map không update được | Phân Phối

### ISSUE THREAD

**Issue by sylarbui** [OCPVietnam/main-bug#8]
## Issue summary
Các google map của các nhà sách sau khi edit đều không thay đổi. Chỉ hiện lên một lần duy nhất, khi bấm qua tab khác thì sẽ trở lại như cũ.

## Screencast (recommended)
http://recordit.co/SB1cVGRsiF

Link: https://ocpvn.org/phan-phoi

**Comment by vyvy0812** [comment]
https://ocpvn.org/phan-phoi/ đã hiển thị được các địa chỉ khác , a check lại giúp em.  http://prntscr.com/mjdjw4
